/** @type {import('prettier').Config} */
module.exports = {
    endOfLine: "lf",
    semi: false,
    singleQuote: false,
    tabWidth: 4,
    trailingComma: "es5",
    // importOrder: [
    //     "^(react/(.*)$)|^(react$)",
    //     "^(next/(.*)$)|^(next$)",
    //     "<THIRD_PARTY_MODULES>",
    //     "",
    //     "^types$",
    //     "^@/types/(.*)$",
    //     "^@/config/(.*)$",
    //     "^@/lib/(.*)$",
    //     "^@/hooks/(.*)$",
    //     "^@/components/ui/(.*)$",
    //     "^@/components/(.*)$",
    //     "^@/registry/(.*)$",
    //     "^@/styles/(.*)$",
    //     "^@/app/(.*)$",
    //     "",
    //     "^[./]",
    // ],
    //
    // importOrderSeparation: true,
    // importOrderSortSpecifiers: true,
    // importOrderBuiltinModulesToTop: true,
    // importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
    // importOrderMergeDuplicateImports: true,
    // importOrderCombineTypeAndValueImports: true,
    importOrder: [
        "^@(assets|components|context|hooks|lib|pages|routes|services|styles|ui|utils)/?(.*)$",
        "^[./]",
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,

    plugins: [
        // '@ianvs/prettier-plugin-sort-imports',
        "@trivago/prettier-plugin-sort-imports",
        "prettier-plugin-tailwindcss",
    ],
}
